describe('cookies localization', function() {

  beforeEach(() => {
    cy.viewport(1366,768)
  })

  it('verifies legal info correspondence to requirements EN', function() {
    cy.visit('https://wolt.com/en/discovery')
    cy.get(':nth-child(1) > .Button__button___1o5LE > span')
      .should('be.visible')
      .click()
    cy.get('.ManageConsentsDialog__root___1ZEAt')
      .should('be.visible')
    cy.get('[data-localization-key="gdpr-consents.manage.required.title"]')
      .should('be.visible')
      .and('have.text', 'Required')
    cy.get('[data-localization-key="gdpr-consents.manage.required.description"]')
      .should('be.visible')
      .and('have.text', 'These cookies are essential so you can move around the website and use its features. Services you have asked for cannot be provided without these cookies.')
    cy.get('[data-localization-key="gdpr-consents.manage.functional.title"]')
      .should('be.visible')
      .and('have.text', 'Functional')
    cy.get('[data-localization-key="gdpr-consents.manage.functional.description"]')
      .should('be.visible')
      .and('have.text', 'These cookies allow the website to remember choices you make to give you better functionality and personal features.')
    cy.get('[data-localization-key="gdpr-consents.manage.analytics.title"]')
      .should('be.visible')
      .and('have.text', 'Analytics (tracking and performance)')
    cy.get('[data-localization-key="gdpr-consents.manage.analytics.description"]')
      .should('be.visible')
      .and('have.text', 'Analytical cookies are used to understand how visitors interact with the website. These cookies help provide information about the number of visitors, how much time they spend on the site, how they have ended up on the site, and more.')
    cy.get('[data-localization-key="gdpr-consents.manage.marketing.title"]')
      .should('be.visible')
      .and('have.text', 'Marketing (targeting and advertising)')
    cy.get('[data-localization-key="gdpr-consents.manage.marketing.description"]')
      .should('be.visible')
      .and('have.text', 'These cookies are used to deliver information to you and to measure the effectiveness of such advertisements. We and our advertising partners will use your data to show you ads that you might be interested in.')    
    })

  it('verifies legal info correspondence to requirements RU', function() {
    cy.visit('https://wolt.com/ru/discovery')
    cy.get(':nth-child(1) > .Button__button___1o5LE > span')
      .should('be.visible')
      .click()
    cy.get('.ManageConsentsDialog__root___1ZEAt')
      .should('be.visible')
    cy.get('[data-localization-key="gdpr-consents.manage.required.title"]')
      .should('be.visible')
      .and('have.text', 'Обязательно ')
    cy.get('[data-localization-key="gdpr-consents.manage.required.description"]')
      .should('be.visible')
      .and('have.text', 'Эти файлы cookie необходимы, чтобы вы могли перемещаться по сайту и использовать его функции. Запрошенные вами услуги не могут быть предоставлены без этих файлов cookie.')
    cy.get('[data-localization-key="gdpr-consents.manage.functional.title"]')
      .should('be.visible')
      .and('have.text', 'Функциональный')
     cy.get('[data-localization-key="gdpr-consents.manage.functional.description"]')
      .should('be.visible')
      .and('have.text', 'Эти файлы cookie позволяют веб-сайту запоминать выбор, который вы делаете, чтобы предоставить вам лучшую функциональность и личные функции.')
    cy.get('[data-localization-key="gdpr-consents.manage.analytics.title"]')
      .should('be.visible')
      .and('have.text', 'Аналитика (отслеживание и производительность)')
    cy.get('[data-localization-key="gdpr-consents.manage.analytics.description"]')
      .should('be.visible')
      .and('have.text', 'Аналитические файлы cookie используются, чтобы понять, как посетители взаимодействуют с сайтом. Эти файлы cookie предоставляют информацию о количестве посетителей, сколько времени они проводят на сайте, как они попали на сайт и многое другое.')
    cy.get('[data-localization-key="gdpr-consents.manage.marketing.title"]')
      .should('be.visible')
      .and('have.text', 'Маркетинг (таргетинг и реклама)')
    cy.get('[data-localization-key="gdpr-consents.manage.marketing.description"]')
      .should('be.visible')
      .and('have.text', 'Эти файлы cookie используются для предоставления информации и измерения эффективности такой рекламы. Мы и наши рекламные партнеры будем использовать ваши данные для показа рекламы, которая может вас заинтересовать.')    
      })
  })