describe('cookies localization', function() {

    beforeEach(function () {
        cy.fixture('cookiesLocalization').then(function (cookiesLocalization) {
            this.cookiesLocalization = cookiesLocalization
        })
    })
  
    it('verifies legal info correspondence to requirements EN', function() {
        cy.viewport(1920, 1080)
        cy.visit(this.cookiesLocalization.baseUrlEN)
        cy.get(':nth-child(1) > .Button__button___1o5LE > span')
          .should('be.visible')
          .click()
        cy.get('.ManageConsentsDialog__root___1ZEAt')
          .should('be.visible')
        cy.get('[data-localization-key="gdpr-consents.manage.required.title"]')
          .should('be.visible')
          .and('have.text', 'Required')
        cy.get('[data-localization-key="gdpr-consents.manage.required.description"]')
          .should('be.visible')
          .contains(this.cookiesLocalization.text1EN)
        cy.get('[data-localization-key="gdpr-consents.manage.functional.title"]')
          .should('be.visible')
          .and('have.text', 'Functional')
        cy.get('[data-localization-key="gdpr-consents.manage.functional.description"]')
          .should('be.visible')
          .contains(this.cookiesLocalization.text2EN)
        cy.get('[data-localization-key="gdpr-consents.manage.analytics.title"]')
          .should('be.visible')
          .and('have.text', 'Analytics (tracking and performance)')
        cy.get('[data-localization-key="gdpr-consents.manage.analytics.description"]')
          .should('be.visible')
          .contains(this.cookiesLocalization.text3EN)
        cy.get('[data-localization-key="gdpr-consents.manage.marketing.title"]')
          .should('be.visible')
          .and('have.text', 'Marketing (targeting and advertising)')
        cy.get('[data-localization-key="gdpr-consents.manage.marketing.description"]')
          .should('be.visible')
          .contains(this.cookiesLocalization.text4EN)
      })

    it('verifies legal info correspondence to requirements RU', function() {
        cy.viewport(360, 640)
        cy.visit(this.cookiesLocalization.baseUrlRU)
        cy.get(':nth-child(1) > .Button__button___1o5LE > span')
          .should('be.visible')
          .click()
        cy.get('.ManageConsentsDialog__root___1ZEAt')
          .should('be.visible')
        cy.get('[data-localization-key="gdpr-consents.manage.required.title"]')
          .should('be.visible')
          .and('have.text', 'Обязательно ')
        cy.get('[data-localization-key="gdpr-consents.manage.required.description"]')
          .should('be.visible')
          .and('have.text', this.cookiesLocalization.text1RU)
        cy.get('[data-localization-key="gdpr-consents.manage.functional.title"]')
          .should('be.visible')
          .and('have.text', 'Функциональный')
         cy.get('[data-localization-key="gdpr-consents.manage.functional.description"]')
          .should('be.visible')
          .and('have.text', this.cookiesLocalization.text2RU)
        cy.get('[data-localization-key="gdpr-consents.manage.analytics.title"]')
          .should('be.visible')
          .and('have.text', 'Аналитика (отслеживание и производительность)')
        cy.get('[data-localization-key="gdpr-consents.manage.analytics.description"]')
          .should('be.visible')
          .and('have.text', this.cookiesLocalization.text3RU)
        cy.get('[data-localization-key="gdpr-consents.manage.marketing.title"]')
          .should('be.visible')
          .and('have.text', 'Маркетинг (таргетинг и реклама)')
        cy.get('[data-localization-key="gdpr-consents.manage.marketing.description"]')
          .should('be.visible')
          .and('have.text', this.cookiesLocalization.text4RU)    
          })   
    })