describe('cookies localization', function() {
  

    const baseUrlen = 'https://wolt.com/en/discovery'
    const baseUrlru = 'https://wolt.com/ru/discovery'

    const text1en = require('C:/Users/HP/cypress/integration/examples/wolt/cookiesLocalText/cookiesLoc_1en.json')
    const text2en = require('C:/Users/HP/cypress/integration/examples/wolt/cookiesLocalText/cookiesLoc_2en.json')
    const text3en = require('C:/Users/HP/cypress/integration/examples/wolt/cookiesLocalText/cookiesLoc_3en.json')
    const text4en = require('C:/Users/HP/cypress/integration/examples/wolt/cookiesLocalText/cookiesLoc_4en.json')

    const text1ru = require('C:/Users/HP/cypress/integration/examples/wolt/cookiesLocalText/cookiesLoc_1ru.json')
    const text2ru = require('C:/Users/HP/cypress/integration/examples/wolt/cookiesLocalText/cookiesLoc_2ru.json')
    const text3ru = require('C:/Users/HP/cypress/integration/examples/wolt/cookiesLocalText/cookiesLoc_3ru.json')
    const text4ru = require('C:/Users/HP/cypress/integration/examples/wolt/cookiesLocalText/cookiesLoc_4ru.json')
 
    it('verifies legal info correspondence to requirements EN', function() {
      cy.viewport(1920, 1080)
      cy.visit(baseUrlen)
      cy.get(':nth-child(1) > .Button__button___1o5LE > span')
        .should('be.visible')
        .click()
      cy.get('.ManageConsentsDialog__root___1ZEAt')
        .should('be.visible')
      cy.get('[data-localization-key="gdpr-consents.manage.required.title"]')
        .should('be.visible')
        .and('have.text', 'Required')
      cy.get('[data-localization-key="gdpr-consents.manage.required.description"]')
        .should('be.visible')
        .and('have.text', text1en)
      cy.get('[data-localization-key="gdpr-consents.manage.functional.title"]')
        .should('be.visible')
        .and('have.text', 'Functional')
      cy.get('[data-localization-key="gdpr-consents.manage.functional.description"]')
        .should('be.visible')
        .and('have.text', text2en)
      cy.get('[data-localization-key="gdpr-consents.manage.analytics.title"]')
        .should('be.visible')
        .and('have.text', 'Analytics (tracking and performance)')
      cy.get('[data-localization-key="gdpr-consents.manage.analytics.description"]')
        .should('be.visible')
        .and('have.text', text3en)
      cy.get('[data-localization-key="gdpr-consents.manage.marketing.title"]')
        .should('be.visible')
        .and('have.text', 'Marketing (targeting and advertising)')
      cy.get('[data-localization-key="gdpr-consents.manage.marketing.description"]')
        .should('be.visible')
        .and('have.text', text4en)    
      })
  
    it('verifies legal info correspondence to requirements RU', function() {
      cy.viewport(360, 640)
      cy.visit(baseUrlru)
      cy.get(':nth-child(1) > .Button__button___1o5LE > span')
        .should('be.visible')
        .click()
      cy.get('.ManageConsentsDialog__root___1ZEAt')
        .should('be.visible')
      cy.get('[data-localization-key="gdpr-consents.manage.required.title"]')
        .should('be.visible')
        .and('have.text', 'Обязательно ')
      cy.get('[data-localization-key="gdpr-consents.manage.required.description"]')
        .should('be.visible')
        .and('have.text', text1ru)
      cy.get('[data-localization-key="gdpr-consents.manage.functional.title"]')
        .should('be.visible')
        .and('have.text', 'Функциональный')
       cy.get('[data-localization-key="gdpr-consents.manage.functional.description"]')
        .should('be.visible')
        .and('have.text', text2ru)
      cy.get('[data-localization-key="gdpr-consents.manage.analytics.title"]')
        .should('be.visible')
        .and('have.text', 'Аналитика (отслеживание и производительность)')
      cy.get('[data-localization-key="gdpr-consents.manage.analytics.description"]')
        .should('be.visible')
        .and('have.text', text3ru)
      cy.get('[data-localization-key="gdpr-consents.manage.marketing.title"]')
        .should('be.visible')
        .and('have.text', 'Маркетинг (таргетинг и реклама)')
      cy.get('[data-localization-key="gdpr-consents.manage.marketing.description"]')
        .should('be.visible')
        .and('have.text', text4ru)    
        })
    })